//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alert
    {
        public int AlertID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string AlertType { get; set; }
        public Nullable<System.DateTime> AlertTime { get; set; }
        public Nullable<bool> EmailSent { get; set; }
        public string Details { get; set; }
    
        public virtual User User { get; set; }
    }
}
